# Core

> Data core utilities

In [ ]:
#| default_exp data.core

In [ ]:
#| hide
from nbdev.showdoc import *
from nbdev.cli import *

In [ ]:
#| export
from brukeropusreader import read_file
import numpy as np
from typing import Tuple, Dict, Callable
import pandas as pd

## Readers

In [ ]:
#| export
def read_opus(
    fname:str # file name
) -> Tuple: # (spectrum, wavenumbers) as `np.ndarray`
    """OPUS (Bruker Optics) infrared spectra reader
    
    It uses patched `brukeropusreader` third party Python package. 
    
    To install it run: 
    `conda install -c "spectrocat/label/dev" brukeropusreader`
    """
    f = read_file(fname)
    return f['AB'], f.get_range('AB')

In [ ]:
fname = 'files/32990XS01.0'
spectrum, wn = read_opus(fname)
print('spectrum:', spectrum)
print('wavenumbers: ', wn)

spectrum: [0.11326975 0.11811147 0.12199899 ... 1.64596999 1.63877058 1.63174832]
wavenumbers:  [7498.04282256 7496.11431361 7494.18580465 ...  603.62330336  601.6947944
  599.76628545]

## Various utilities

In [ ]:
#| export
def select_rows(df:pd.DataFrame, #  DataFrame whose rows should be selected
                where:Dict[str, Callable], # Pandas columns as keys & predicates as values.
               ) -> pd.DataFrame:
    "When passed to Pandas pipe, perform row selection given multiple predicates"
    df = df.copy()
    for col, f in where.items():
        df = df[df[col].apply(f)]
    return df

For instance, given the `pd.DataFrame` below:

In [ ]:
df  = pd.DataFrame({'col1': [1,2,3,4], 'col2': [11, 12, 13, 14]}); df

   col1  col2
0     1    11
1     2    12
2     3    13
3     4    14

Allow rows selection based on multiple criteria:

In [ ]:
df.pipe(select_rows, 
        {'col1': lambda d: d > 1, 'col2': lambda d: not(d % 2)})

   col1  col2
1     2    12
3     4    14

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()